baseURL: https://zottner.com/
languageCode: en-us
title: Marc Zottner
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-T9E42JFPBE

disableKinds: ["term", "taxonomy"]

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Marc Zottner | Application Archeologist | Fellow & Field CTO | IT Modernization
  description: "Application Archeologist, Field CTO, and Executive Advisor specializing in modernization, cloud-native transformation, and enterprise architecture."
  keywords: [Application Modernization, Cloud Native, Architecture, Legacy Systems, VMware Tanzu]
  author: Marc Zottner
  images: ["https://avatars.githubusercontent.com/u/2445024?v=4"]
  DateFormat: "January 3, 2026"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: true
  showtoc: false
  tocopen: false

  assets:
    favicon: "./favicon.png"
    favicon16x16: "./favicon.png"
    favicon32x32: "./favicon.png"
    apple_touch_icon: "./favicon.png"
    safari_pinned_tab: "./favicon.png"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Marc Zottner
    subtitle: Application Archeologist & Advisor
    imageUrl: "https://avatars.githubusercontent.com/u/2445024?v=4"
    imageWidth: 260
    imageHeight: 260
    imageTitle: Me

  socialIcons:
    - name: linkedin
      title: "LinkedIn Profile"
      url: "https://www.linkedin.com/in/marczottner/"
    - name: xing
      title: "Xing Profile"
      url: "https://www.xing.com/profile/Marc_Zottner"
    - name: github
      title: "GitHub Profile"
      url: "https://github.com/maarc/"
    - name: twitter
      title: "Twitter Profile"
      url: "https://twitter.com/MarcZottner"
    - name: soundcloud
      title: "SoundCloud Profile"
      url: "https://soundcloud.com/true-dj-raffe"

  analytics:
    google:
      SiteVerificationTag: ""

  schema:
    publisherType: "Person"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: material
      name: Material
      url: /material/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false

server:
  headers:
  - for: "/*"
    values:
      Content-Security-Policy: "default-src 'self' 'unsafe-eval' 'unsafe-inline' www.google-analytics.com www.googletagmanager.com avatars.githubusercontent.com;"
      Access-Control-Allow-Origin: 'http://zottner.com'
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
      X-Content-Type-Options: "nosniff"
      Referrer-Policy: "strict-origin-when-cross-origin"
      Strict-Transport-Security: "max-age=2592000; includeSubDomains; preload"

