baseURL: https://maarc.github.io/
languageCode: en-us
title: Marc Zottner
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-133419934-1

disableKinds: ["term", "taxonomy", "taxonomyTerm", "sitemap"]

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Marc Zottner
  description: "Personal page"
  keywords: [Blog, Application, Modernization]
  author: Marc Zottner
  DateFormat: "January 3, 2023"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: true
  showtoc: false
  tocopen: false

  assets:
    favicon: "./favicon.png"
    favicon16x16: "./favicon.png"
    favicon32x32: "./favicon.png"
    apple_touch_icon: "./favicon.png"
    safari_pinned_tab: "./favicon.png"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Marc Zottner
    subtitle: Application Archeologist & Advisor
    imageUrl: "https://avatars.githubusercontent.com/u/2445024?v=4"
    imageWidth: 260
    imageHeight: 260
    imageTitle: Me

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/marczottner/"
    - name: xing
      url: "https://www.xing.com/profile/Marc_Zottner"
    - name: github
      url: "https://github.com/maarc/"
    - name: twitter
      url: "https://twitter.com/MarcZottner"
    - name: soundcloud
      url: "https://soundcloud.com/true-dj-raffe"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: material
      name: material
      url: material
      weight: 10
    - identifier: about
      name: about
      url: about
      weight: 20


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false

